name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "27"
        rebar3-version: "3"

    - name: Check format
      run: make fmt-check

    - name: Run tests
      run: |
        make run
        make eunit
        make ct

  release:
    name: Publish release
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "27"
        rebar3-version: "3"

    - name: Build Release
      run: make rel

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: _build/default/emqx_plugrel/emqx_sdv-*.tar.gz
        generate_release_notes: true
